include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    require_trailing_commas: true
    use_key_in_widget_constructors: true
    avoid_init_to_null: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    camel_case_types: true
    file_names: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
