# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

ENV["ANDROID_APP_ID"] = "1:257562948724:android:5db3214660447c21240d21"

platform :android do
  lane :increment_build_and_version_number do
    gradle_file = "./app/build.gradle"
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["ANDROID_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    )

    if latest_release.nil?
      current_version = "1.0.0"
      current_build = "0"
      new_version = current_version
      UI.message("No previous releases found, setting version number to #{current_version}")
    else
      current_version = latest_release[:displayVersion]
      current_build = latest_release[:buildVersion]
      # Split the version number into its components
      version_parts = current_version.split(".")
      
      # Increment the minor version and reset the patch version
      version_parts[2] = (version_parts[2].to_i + 1).to_s
      
      new_version = version_parts.join(".")
      UI.message("Incrementing version number to #{new_version}")
    end

    # if you want to increment version name add `--build-name=#{new_version}` to the command
    sh "flutter build apk --release --build-name=#{new_version} --build-number=#{current_build.to_i + 1}"
  end

  desc "Lane to build and distribute the android app"
  lane :firebase_distribution do
    sh "flutter clean"
    increment_build_and_version_number
    firebase_app_distribution(
      app: ENV["ANDROID_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      upload_timeout: 5000,
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "hosamafiky@gmail.com, yara1assad@gmail.com",
      release_notes: "This is a beta release of the app",
    )
  end
end
